// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd3fw5Zt9bCDxWM0tTLLJ25ikp_IjKkuU',
    appId: '1:167117067529:web:53feeab4d29d81c4d66fd8',
    messagingSenderId: '167117067529',
    projectId: 'juneauth-4a08c',
    authDomain: 'juneauth-4a08c.firebaseapp.com',
    storageBucket: 'juneauth-4a08c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRu6Nw9WDccbAIehy1ztDPiu1Mp1uDPYQ',
    appId: '1:167117067529:android:5169e6d8997c5c6ad66fd8',
    messagingSenderId: '167117067529',
    projectId: 'juneauth-4a08c',
    storageBucket: 'juneauth-4a08c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA07LuT3j9zIBQ36UFtVT3Q_bXS5_o2F6A',
    appId: '1:167117067529:ios:ba3351fc704dee31d66fd8',
    messagingSenderId: '167117067529',
    projectId: 'juneauth-4a08c',
    storageBucket: 'juneauth-4a08c.firebasestorage.app',
    iosBundleId: 'com.example.myAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA07LuT3j9zIBQ36UFtVT3Q_bXS5_o2F6A',
    appId: '1:167117067529:ios:ba3351fc704dee31d66fd8',
    messagingSenderId: '167117067529',
    projectId: 'juneauth-4a08c',
    storageBucket: 'juneauth-4a08c.firebasestorage.app',
    iosBundleId: 'com.example.myAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd3fw5Zt9bCDxWM0tTLLJ25ikp_IjKkuU',
    appId: '1:167117067529:web:8e2a16122cfbff80d66fd8',
    messagingSenderId: '167117067529',
    projectId: 'juneauth-4a08c',
    authDomain: 'juneauth-4a08c.firebaseapp.com',
    storageBucket: 'juneauth-4a08c.firebasestorage.app',
  );
}
