// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQDe4A0zTr5XJ_1y_yrUfQLwoO44Qbap0',
    appId: '1:714836219217:web:395e6a02acf4abb33e6f70',
    messagingSenderId: '714836219217',
    projectId: 'backendjune-774c3',
    authDomain: 'backendjune-774c3.firebaseapp.com',
    storageBucket: 'backendjune-774c3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvCbEiJtH7IKMbZkOn1SyrB83-zhh9qxE',
    appId: '1:714836219217:android:f997cf8b860b9b553e6f70',
    messagingSenderId: '714836219217',
    projectId: 'backendjune-774c3',
    storageBucket: 'backendjune-774c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaC_3n5nJsBEuC_nX_dpve6-3qoLfxvX0',
    appId: '1:714836219217:ios:41b6eaa7be18c7ae3e6f70',
    messagingSenderId: '714836219217',
    projectId: 'backendjune-774c3',
    storageBucket: 'backendjune-774c3.firebasestorage.app',
    iosBundleId: 'com.example.myFronBackend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaC_3n5nJsBEuC_nX_dpve6-3qoLfxvX0',
    appId: '1:714836219217:ios:41b6eaa7be18c7ae3e6f70',
    messagingSenderId: '714836219217',
    projectId: 'backendjune-774c3',
    storageBucket: 'backendjune-774c3.firebasestorage.app',
    iosBundleId: 'com.example.myFronBackend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQDe4A0zTr5XJ_1y_yrUfQLwoO44Qbap0',
    appId: '1:714836219217:web:c6db801d72130a7b3e6f70',
    messagingSenderId: '714836219217',
    projectId: 'backendjune-774c3',
    authDomain: 'backendjune-774c3.firebaseapp.com',
    storageBucket: 'backendjune-774c3.firebasestorage.app',
  );
}
